##graphing script
library(dplyr)
library(hms)
library(ggplot2)
library(easyGgplot2)
library(lattice)
library(futile.logger)
library(vitalsignprocessor)
library(LaplacesDemon)
library(ggpubr)

pdf(file = paste("Plots.pdf",sep = ""),height = 100, width = 20)
theme_set(theme_classic()+theme(legend.position="top"))
operationrooms <- c("OR1","OR2","OR3","OR4","OR5","OR6","OR7","DENTAL","CT","CATH")
#operationrooms <- c("OR1","OR2")
headers <- c("HR","NIBPsys","NIBPdia","NIBPmean","PR.P1.","T1","SpO2","PR.SpO2.","EtCO2","RR.CO2.","FeO2","FiO2","FeN2O","FiN2O","FeAA","FiAA","MAC","Ppeak","PEEP","TVinsp","TVexp","MVexp","P1sys","P1dia","P1mean","Compl")
#headers <- c("HR")
FILE_POSTFIX <- "_coverageresult.csv"
plotter <- ggplotter$new()
plist <- plotter$getplots(operationrooms, headers)
#print("###################################")
#print(finalist[["OR6 HR"]])
#print("###################################")
#print(finalist[["OR1 HR"]])
#print("###################################")
#print(finalist[["HR summary"]])
result_plots <- multiplot(plotlist=plist,cols = length(operationrooms)+1)
print(result_plots)
dev.off()
flog.info("graph generation completed")

#variables <- c("HR","ST1","NIBPsys","NIBPdia","NIBPmean","PR.NIBP.","T1","SpO2","PR.SpO2.","EtCO2","FiCO2","RR.CO2.","FeO2","FiO2","FeN2O","FiN2O","FeAA","FiAA","MAC","RR.Spiro.","Ppeak","PEEP","TVinsp","TVexp","Compl","MVexp","PTC","HR.ECG.","HRmax","HRmin")
#variables <- c("HR")
#print(plotter$getmetadata(plist,variables))
